name: Linux

on: [push, pull_request]

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildtype: [Debug, Release, MinSizeRel, Coverage]
        cxx: [clang++, g++]
    
    steps:
    - uses: actions/checkout@v1

    - name: Generate build system
      run: CXX="${{ matrix.cxx }}" cmake -DCMAKE_BUILD_TYPE="${{ matrix.buildtype }}" .

    - name: Build
      run: cmake --build . --target tests 

    - name: Test
      run: ./tests

    - name: Coverage
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
      env:
        CODECOV_TOKEN: 541a3b5e-4f2f-436d-a38b-8309f5819e9c
      if: matrix.buildtype == 'Coverage'
