name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1

    - name: Generate build system
      run: cmake .

    - name: Build
      run: cmake --build . --target tests -D CMAKE_BUILD_TYPE=MinSizeRel

    - name: Run (UNIX)
      run: ./tests
      if: matrix.os != 'windows-latest'

    - name: Run (Windows)
      run: Release\tests.exe
      if: matrix.os == 'windows-latest'
